FROM ubuntu:18.04

#RUN useradd -ms /bin/bash meshbits
RUN apt-get -y update && apt-get -y install sudo
ADD . /usr/local/src/komodo_scripts
RUN /usr/local/src/komodo_scripts/bin/create_user.sh meshbits
USER meshbits
WORKDIR /home/meshbits
RUN /usr/local/src/komodo_scripts/bin/setup_komodo.sh


CMD ["/bin/bash"]
