FROM ubuntu:16.04

#RUN useradd -ms /bin/bash meshbits
RUN apt-get -y -qq update && apt-get -y -qq install sudo time curl
ADD . /usr/local/src/komodo_scripts

RUN /usr/local/src/komodo_scripts/bin/create_user.sh meshbits
RUN /usr/local/src/komodo_scripts/bin/userdata.sh

USER meshbits
WORKDIR /home/meshbits

RUN /usr/local/src/komodo_scripts/bin/setup_komodo.sh

CMD ["/bin/bash"]
